#ifndef J1939MESSAGE_H
#define J1939MESSAGE_H

/**
 * Generated by C-Next Transpiler from: J1939Message.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct J1939Message {
    uint32_t canId;
    uint8_t sourceAddress;
    uint16_t pgn;
    uint8_t pduFormat;
    uint8_t pduSpecific;
    uint8_t priority;
    uint8_t data[8];
} J1939Message;

/* Function prototypes */
void J1939_init(J1939Message* msg);
void J1939_setCanId(J1939Message* msg, uint32_t canId);
void J1939_setData(J1939Message* msg, const uint8_t data[8]);
uint8_t J1939_getSourceAddress(uint32_t canId);
uint32_t J1939_setSourceAddress(J1939Message* msg, uint8_t sourceAddress);
uint16_t J1939_getPgn(uint32_t canId);
uint32_t J1939_setPgn(J1939Message* msg, uint16_t pgn);
uint8_t J1939_getPduSpecific(uint32_t canId);
uint32_t J1939_setPduSpecific(J1939Message* msg, uint8_t pduSpecific);
uint8_t J1939_getPduFormat(uint32_t canId);
uint32_t J1939_setPduFormat(J1939Message* msg, uint8_t pduFormat);
uint8_t J1939_getPriority(uint32_t canId);
uint32_t J1939_setPriority(J1939Message* msg, uint8_t priority);

#ifdef __cplusplus
}
#endif

#endif /* J1939MESSAGE_H */
