/**
 * Generated by C-Next Transpiler from: J1939Message.cnx
 * A safer C for embedded systems
 */

#include "J1939Message.h"

#include <stdint.h>

/* Scope: J1939 */

void J1939_init(J1939Message* msg) {
    msg->canId = 0x80000000U;
    msg->sourceAddress = 0U;
    msg->pgn = 0U;
    msg->pduFormat = 0U;
    msg->pduSpecific = 0U;
    msg->priority = 0U;
    for (uint8_t i = 0; i < 8; i += 1) {
        msg->data[i] = 0xFFU;
    }
}

void J1939_setCanId(J1939Message* msg, uint32_t canId) {
    msg->canId = canId;
    msg->sourceAddress = (uint8_t)((canId) & 0xFFU);
    msg->pgn = (uint16_t)((canId >> 8U) & 0xFFFFU);
    msg->pduSpecific = (uint8_t)((canId >> 8U) & 0xFFU);
    msg->pduFormat = (uint8_t)((canId >> 16U) & 0xFFU);
    msg->priority = (uint8_t)((canId >> 26U) & ((1U << 3U) - 1));
}

void J1939_setData(J1939Message* msg, const uint8_t data[8]) {
    for (uint8_t i = 0; i < 8; i += 1) {
        msg->data[i] = data[i];
    }
}

uint8_t J1939_getSourceAddress(uint32_t canId) {
    return ((canId) & 0xFFU);
}

uint32_t J1939_setSourceAddress(J1939Message* msg, uint8_t sourceAddress) {
    msg->sourceAddress = sourceAddress;
    uint32_t id = msg->canId;
    id = (id & ~(0xFFU << 0)) | ((sourceAddress & 0xFFU) << 0);
    msg->canId = id;
    return msg->canId;
}

uint16_t J1939_getPgn(uint32_t canId) {
    return ((canId >> 8U) & 0xFFFFU);
}

uint32_t J1939_setPgn(J1939Message* msg, uint16_t pgn) {
    msg->pgn = pgn;
    msg->pduSpecific = (uint8_t)((pgn) & 0xFFU);
    msg->pduFormat = (uint8_t)((pgn >> 8U) & 0xFFU);
    uint32_t id = msg->canId;
    id = (id & ~(0xFFFFU << 8)) | ((pgn & 0xFFFFU) << 8);
    msg->canId = id;
    return msg->canId;
}

uint8_t J1939_getPduSpecific(uint32_t canId) {
    return ((canId >> 8U) & 0xFFU);
}

uint32_t J1939_setPduSpecific(J1939Message* msg, uint8_t pduSpecific) {
    msg->pduSpecific = pduSpecific;
    uint32_t id = msg->canId;
    id = (id & ~(0xFFU << 8)) | ((pduSpecific & 0xFFU) << 8);
    msg->canId = id;
    return msg->canId;
}

uint8_t J1939_getPduFormat(uint32_t canId) {
    return ((canId >> 16U) & 0xFFU);
}

uint32_t J1939_setPduFormat(J1939Message* msg, uint8_t pduFormat) {
    msg->pduFormat = pduFormat;
    uint32_t id = msg->canId;
    id = (id & ~(0xFFU << 16)) | ((pduFormat & 0xFFU) << 16);
    msg->canId = id;
    return msg->canId;
}

uint8_t J1939_getPriority(uint32_t canId) {
    return ((canId >> 26U) & ((1U << 3U) - 1));
}

uint32_t J1939_setPriority(J1939Message* msg, uint8_t priority) {
    msg->priority = priority;
    uint32_t id = msg->canId;
    id = (id & ~(((1U << 3) - 1) << 26)) | ((priority & ((1U << 3) - 1)) << 26);
    msg->canId = id;
    return msg->canId;
}
